### ISSUE TITLE
Presentations on non-touch displays

### ISSUE THREAD

**Issue by normanjaeckel** [jugglinmike/presentations#1]
Is it possible to change the JS that one can have a look at the presentations on non-touch displays (maybe using click or key events)?

**Comment by jugglinmike** [comment]
This repo contains presentations written with a few different JavaScript frameworks for slideshows (three I think). I didn't author any of them to be touch-only, though: can you be more specific with the problem you are having?

**Comment by jugglinmike** [comment]
@normanjaeckel It's been a few weeks, but I haven't heard back from you. Without more information, I won't be able to help. Please re-open this issue with more information if you're still having trouble

**Comment by normanjaeckel** [comment]
Sorry. I forgot this ...
I checked out the repo and just opened 2014/write-right-tests/index.html in Firefox 35.0.1 from the filesystem. There it is not possbile to switch between slides. I just can scroll the whole presentation but don't know where a slide ends and a new one begins.
The function `isTouchDevice()` in slides.js line 202 returns false so I thought the presentation is not made for non touch devices.
I can not reopen this issue because I don't have the required GitHub permission.

**Comment by jugglinmike** [comment]
Ah, now I understand. You can view the content, you just can't step through the slides.

This a feature of [the Slide framework](http://static.incompl.com/slide/)--clients with JavaScript disabled are still able to view all the content. If you'd like to view the presentation as a slide show, hit the "escape" key.

**Comment by normanjaeckel** [comment]
Ah "Escape" works. Thanks.
