### ISSUE TITLE
Would you add BostonJS git presentation?

### ISSUE THREAD

**Issue by rmharrison** [jugglinmike/presentations#2]
Hey Mike,

I really enjoyed your git presentation in Oct at BostonJS [[1]](https://www.meetup.com/boston_JS/events/233805265/). Would you include the source for the presentation?

In particularly, I'm interested in the terminal examples using [repl-sim](https://github.com/jugglinmike/repl-sim).

cc: @jenweber

**Comment by jugglinmike** [comment]
Hey there, Ryan! Here you go:

https://jugglinmike.github.io/presentations/2016/git-in-layers/

I kind of dropped the ball on this one; thanks for reminding me.

If you'd like more examples of `repl-sim`, then you should check out "Command
the Command Line," an open workshop I created for Bocoup last year

- Source: https://github.com/bocoup-education/command-the-command-line
- Site: https://bocoup-education.github.io/command-the-command-line/

If you end up using `repl-sim` in any of your work, please let me know. I'd
love to see what you come up with :)
